# Generated by Django 2.2.24 on 2021-07-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachmet',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
