# Generated by Django 2.2.24 on 2021-07-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210715_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachmet',
            field=models.FileField(blank=True, default=None, upload_to='attachmet'),
        ),
    ]
