# Generated by Django 2.2.11 on 2020-04-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200421_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
