# Generated by Django 2.2.24 on 2021-07-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210715_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attachmet',
        ),
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, default=None, upload_to='attachment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
