# Generated by Django 2.2.11 on 2020-04-21 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_postdeslike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostDesLike',
        ),
    ]
