# Generated by Django 2.2.24 on 2021-07-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210715_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(default=None, upload_to='attachment/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default=None, upload_to='media2/'),
        ),
    ]
